### ISSUE TITLE
Stardist seems not to work with python 3.9

### ISSUE THREAD

**Issue by Cocomolch4000** [stardist/stardist#139]
Tested on Windows and Linux. Installation with pip worked flawlessly using python 3.8.9. With python 3.9.4 h5py seems to have some kind of problem during the installation. Would be great to add this to the readme so people can simply use the old python version.
Regards
Cocomolch4000

**Comment by uschmidt83** [comment]
Hi, the latest stable version of TensorFlow currently doesn't support Python 3.9, which is required by StarDist.
Hence, we haven't even tested StarDist with Python 3.9+.

Best,
Uwe

**Comment by Cocomolch4000** [comment]
Hi,

alright! I just thought that it might be helpful to indicate this on your github page. 
There, it is indicated that stardist works for python >3.6. So maybe indicating >3.6 <3.9 would be helpful for other users.
Just a suggestion.

Best
Cocomolch4000

**Comment by maweigert** [comment]
Hi @Cocomolch4000 ,

This is a good point - we've just updated the Readme to reflect this. Thanks for the feedback!

**Comment by Cocomolch4000** [comment]
No problem, thanks for the great tool!

**Comment by alandegenhart** [comment]
I may be running into a similar issue when attempting to install into a new Python 3.8.8 conda environment on Mac.  The latest stable version of TensorFlow requires h5py~=3.1.0, while csbdeep 0.6.1 requires h5py<3.

**Comment by maweigert** [comment]
Hi @alandegenhart ,

Yes, there [has been an issue ](https://github.com/tensorflow/tensorflow/issues/44467) with h5py>2.10 for older tensorflow versions, which is why we pinned the h5py version to 2.10. So reinstalling it via `pip install -U h5py` should work for you.

PS: @Cocomolch4000: Just some moments ago, tensorflow 2.5.0 was released, so python 3.9 should be then also work (in principle :).

**Comment by Cocomolch4000** [comment]
Good to hear! :)

**Comment by maweigert** [comment]
Python 3.9 support was added from version `0.7.0` on
