### ISSUE TITLE
Unpin numpy version in pyproject.toml

### ISSUE THREAD

**Issue by weinberz** [stardist/stardist#156]
When trying to install stardist from pip on Apple Silicon, build will fail because it requires numpy==1.19.3 but Apple Silicon native numpy is 1.19.5 and up*. Any chance you can unpin the version in pyproject.toml if there's not a specific dependency here?

*This is derived from info at https://forum.image.sc/t/napari-tensorflow-aicsimageio-stardist-pyclesperanto-running-native-on-apple-silicon-m1/55051

Thanks!

**Comment by uschmidt83** [comment]
Hi @weinberz, thanks for opening an issue.

I was already investigating this after I saw the [forum post](https://forum.image.sc/t/napari-tensorflow-aicsimageio-stardist-pyclesperanto-running-native-on-apple-silicon-m1/55051), since I also have a Mac based on Apple Silicon.

> Any chance you can unpin the version in pyproject.toml if there's not a specific dependency here?

There was a good reason for the pinned numpy version (cf. [release notes](https://github.com/stardist/stardist/releases/tag/0.6.1)), but this seems no longer relevant. I "just" have to figure out to what to change this to (cf. [relevant section of scipy's `pyproject.toml` file](https://github.com/scipy/scipy/blob/47af6102fc5a900c5008bc4ad8415ad2a136c92c/pyproject.toml#L18-L46)).

In the meantime, I'll see whether I can build a wheel for Apple Silicon and upload it for the current release of StarDist. This will likely solve most people's problems, since `pyproject.toml` is only needed during installation if there are no wheels available.

**Comment by uschmidt83** [comment]
Ok, installation via `CC=gcc-11 CXX=g++-11 pip install git+https://github.com/stardist/stardist@dev` should work now (assuming gcc-11 is installed as in the [forum post](https://forum.image.sc/t/napari-tensorflow-aicsimageio-stardist-pyclesperanto-running-native-on-apple-silicon-m1/55051)).

**Comment by weinberz** [comment]
Amazing! Thanks so much Uwe!

**Comment by uschmidt83** [comment]
Hi @weinberz, the latest release (0.7.2) fixes this issue and is now on PyPI, i.e. you can install it via `CC=gcc-11 CXX=g++-11 pip install stardist`.

**Comment by psobolewskiPhD** [comment]
FYI: This does work (builds fine), but stardist won’t import.
In a fresh apple-TF env, after using conda to get numba and scikit-image.
The build succeeds, but then when I try to import I get:
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
and traceback shows:
```
ImportError: numpy.core.multiarray failed to import
```
This can be fixed by installing numpy 1.21.0:
`pip install numpy==1.21.0`
This of course gives warning regarding TF requirements, but stardist imports and the example code runs.
(Previously, I’ve had to install numpy 1.21.0 into a TF-StarDist env to get napari running and i’ve been using with tf/stardist just fine, but your milage may vary.)

**Comment by uschmidt83** [comment]
See my reply at the [image.sc forum](https://forum.image.sc/t/napari-tensorflow-aicsimageio-stardist-pyclesperanto-running-native-on-apple-silicon-m1/55051/13).

> In the meantime, I'll see whether I can build a wheel for Apple Silicon and upload it for the current release of StarDist. This will likely solve most people's problems, since `pyproject.toml` is only needed during installation if there are no wheels available.

PS: I wanted to also build wheels for Apple Silicon, but decided that it's too much work at the moment. I also can't automate it, like I do for the other platforms.

**Comment by psobolewskiPhD** [comment]
Gotcha. I just followed Apple’s TensorFlow instructions and then your instructions and it didn’t work, so I wanted to make sure others knew.
Apple’s TF install comes with a lot of stuff, including numpy. It works. And StarDist works—with the edit to the numpy requirement.
If someone has an existing env with numpy 1.21.0 it's all good. But someone new following instructions will hit the snag.
I’ve used Numpy 1.21.0 to get napari working and it also works in my experience—I’ve done some dask-stardist stuff on real data.
