### ISSUE TITLE
Dataset TOY

### ISSUE THREAD

**Issue by gatoniel** [stardist/stardist#30]
Hi,

I am working on some changes of your network to adapt it to our own circumstances. I would like to test my changes on your dataset TOY, or at least similar pictures. Is it possible to share your code to generate this dataset or share the dataset?

Best,
Niklas

**Comment by uschmidt83** [comment]
Hi @gatoniel,

your request somehow slipped through my radar at the time, and I only notice this now since someone else wanted that dataset. I'm sorry.

In the unlikely event that you're still interested, you can download it [here](https://www.dropbox.com/s/4lmt0vqb59t309u/stardist_toy.zip?dl=1).

Best,
Uwe
